DROP TABLE IF EXISTS public.UserAccount CASCADE;
DROP SEQUENCE IF EXISTS UserAccountSeq;

DROP TABLE IF EXISTS public.Session CASCADE;
DROP TABLE IF EXISTS public.SampleMessage CASCADE;
DROP SEQUENCE IF EXISTS SampleMessageSeq;

DROP TABLE IF EXISTS public.Message CASCADE;
DROP SEQUENCE IF EXISTS MessageSeq;

DROP TABLE IF EXISTS public.ToDoDetail CASCADE;
DROP SEQUENCE IF EXISTS ToDoDetailSeq;

DROP TABLE IF EXISTS public.Todo CASCADE;
DROP SEQUENCE IF EXISTS TodoSeq;

DROP TABLE IF EXISTS public.SampleProduct CASCADE;
DROP SEQUENCE IF EXISTS SampleProductSeq;

DROP TABLE IF EXISTS public.Userlogin CASCADE;
DROP SEQUENCE IF EXISTS UserloginSeq;
